package POJOS;
// Generated 07-jun-2022 18:31:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Central generated by hbm2java
 */
public class Central  implements java.io.Serializable {


     private String nombre;
     private String direccion;
     private String email;
     private int telefono;
     private Set sucursals = new HashSet(0);

    public Central() {
    }

	
    public Central(String nombre, String direccion, String email, int telefono) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.email = email;
        this.telefono = telefono;
    }
    public Central(String nombre, String direccion, String email, int telefono, Set sucursals) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.email = email;
       this.telefono = telefono;
       this.sucursals = sucursals;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Set getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set sucursals) {
        this.sucursals = sucursals;
    }




}


