package POJOS;
// Generated 07-jun-2022 18:31:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private Integer id;
     private Central central;
     private String direccion;
     private Set usuarios = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(Central central, String direccion) {
        this.central = central;
        this.direccion = direccion;
    }
    public Sucursal(Central central, String direccion, Set usuarios) {
       this.central = central;
       this.direccion = direccion;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Central getCentral() {
        return this.central;
    }
    
    public void setCentral(Central central) {
        this.central = central;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


