package POJOS_UPOBank;
// Generated 05-jun-2022 18:04:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bizum generated by hbm2java
 */
public class Bizum  implements java.io.Serializable {


     private Integer id;
     private CuentaBancaria cuentaBancaria;
     private int movilDestinatario;
     private Date fecha;
     private float cantidad;

    public Bizum() {
    }

    public Bizum(CuentaBancaria cuentaBancaria, int movilDestinatario, Date fecha, float cantidad) {
       this.cuentaBancaria = cuentaBancaria;
       this.movilDestinatario = movilDestinatario;
       this.fecha = fecha;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CuentaBancaria getCuentaBancaria() {
        return this.cuentaBancaria;
    }
    
    public void setCuentaBancaria(CuentaBancaria cuentaBancaria) {
        this.cuentaBancaria = cuentaBancaria;
    }
    public int getMovilDestinatario() {
        return this.movilDestinatario;
    }
    
    public void setMovilDestinatario(int movilDestinatario) {
        this.movilDestinatario = movilDestinatario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }




}


