package POJOS_UPOBank;
// Generated 05-jun-2022 18:04:24 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String dni;
     private CuentaBancaria cuentaBancaria;
     private Sucursal sucursal;
     private String nombreCompleto;
     private int password;
     private String direccion;
     private int movil;

    public Usuario() {
    }

    public Usuario(String dni, CuentaBancaria cuentaBancaria, Sucursal sucursal, String nombreCompleto, int password, String direccion, int movil) {
       this.dni = dni;
       this.cuentaBancaria = cuentaBancaria;
       this.sucursal = sucursal;
       this.nombreCompleto = nombreCompleto;
       this.password = password;
       this.direccion = direccion;
       this.movil = movil;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public CuentaBancaria getCuentaBancaria() {
        return this.cuentaBancaria;
    }
    
    public void setCuentaBancaria(CuentaBancaria cuentaBancaria) {
        this.cuentaBancaria = cuentaBancaria;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public int getPassword() {
        return this.password;
    }
    
    public void setPassword(int password) {
        this.password = password;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getMovil() {
        return this.movil;
    }
    
    public void setMovil(int movil) {
        this.movil = movil;
    }

    @Override
    public String toString() {
        return "Usuario{" + "dni=" + dni + ", cuentaBancaria=" + cuentaBancaria + ", sucursal=" + sucursal + ", nombreCompleto=" + nombreCompleto + ", password=" + password + ", direccion=" + direccion + ", movil=" + movil + '}';
    }




}


