package Modelo;
// Generated 01-jun-2022 11:27:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transferencia generated by hbm2java
 */
public class Transferencia  implements java.io.Serializable {


     private Integer id;
     private CuentaBancaria cuentaBancaria;
     private String ibanDestinatario;
     private Date fechaInicio;
     private Date fechaFin;
     private float cantidad;

    public Transferencia() {
    }

    public Transferencia(CuentaBancaria cuentaBancaria, String ibanDestinatario, Date fechaInicio, Date fechaFin, float cantidad) {
       this.cuentaBancaria = cuentaBancaria;
       this.ibanDestinatario = ibanDestinatario;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CuentaBancaria getCuentaBancaria() {
        return this.cuentaBancaria;
    }
    
    public void setCuentaBancaria(CuentaBancaria cuentaBancaria) {
        this.cuentaBancaria = cuentaBancaria;
    }
    public String getIbanDestinatario() {
        return this.ibanDestinatario;
    }
    
    public void setIbanDestinatario(String ibanDestinatario) {
        this.ibanDestinatario = ibanDestinatario;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }




}


