package Modelo;
// Generated 01-jun-2022 11:27:02 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String dni;
     private CuentaBancaria cuentaBancaria;
     private Sucursal sucursal;
     private String nombreCompleto;
     private String direccion;
     private int movil;

    public Usuario() {
    }

    public Usuario(String dni, CuentaBancaria cuentaBancaria, Sucursal sucursal, String nombreCompleto, String direccion, int movil) {
       this.dni = dni;
       this.cuentaBancaria = cuentaBancaria;
       this.sucursal = sucursal;
       this.nombreCompleto = nombreCompleto;
       this.direccion = direccion;
       this.movil = movil;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public CuentaBancaria getCuentaBancaria() {
        return this.cuentaBancaria;
    }
    
    public void setCuentaBancaria(CuentaBancaria cuentaBancaria) {
        this.cuentaBancaria = cuentaBancaria;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getMovil() {
        return this.movil;
    }
    
    public void setMovil(int movil) {
        this.movil = movil;
    }




}


